package com.sbnz;

//list any import classes here.

import com.sbnz.physio.facts.*;


rule "Dynamic to static"
    when
        $t1: ExcerciseEvent(painType == ExcerciseEvent.PainType.STIFFNESS, type == Excercise.Type.DYNAMIC, $name: name)
    then
       insert(new ExerciseReplacement(Excercise.Type.STATIC, $name));
end

rule "Static to rest"
    when
        $t1: ExcerciseEvent((painType == ExcerciseEvent.PainType.STIFFNESS || painType == ExcerciseEvent.PainType.PAIN), 
        					type == Excercise.Type.STATIC, $name: name)
    then
       insert(new ExerciseReplacement(Excercise.Type.REST, $name));
end