//created on: May 22, 2022
package com.sbnz;

//list any import classes here.

import com.sbnz.physio.facts.*;
import java.time.LocalDate;
import java.util.List;

//declare any global variables here




rule "Classify pain - Cervical Mechanical"

    when
    	$d : Diagnosis(illness == null)
        $p : Pain(
        	painType == null, painLocalization == null,
        	$symptoms: symptoms
        )
        Pain.Symptoms(this == Pain.Symptoms.NECK_PAIN_EXTENDING_INTO_NAPE) from $symptoms
        Number($value: intValue > 1) from accumulate(
        	Pain.Symptoms(
        			$t: this, 
        			this == Pain.Symptoms.MUSCLE_SPASM ||
        			this == Pain.Symptoms.MOVEMENT_PAIN ||
        			this == Pain.Symptoms.EXTENDED_POSITION_PAIN
        		) from $symptoms, 
        	count($t)
        )
    then
        modify($p) { 
        	setPainLocalization(Pain.PainLocalization.CERVICAL), 
        	setPainType(Pain.PainType.MECHANICAL); 
        }
        
end



rule "Classify pain - Cervical Neurological"

    when
    	$d : Diagnosis(illness == null)
        $p : Pain(
        	painType == null, painLocalization == null,
        	$symptoms: symptoms
        )
        Number($value: intValue > 1) from accumulate(
        	Pain.Symptoms(
        			$t: this, 
        			this == Pain.Symptoms.SHARP_NON_EXTENDING_NECK_PAIN ||
        			this == Pain.Symptoms.SHOULDER_AND_ARM_ELECTRIC_PAIN ||
        			this == Pain.Symptoms.ARM_AND_HAND_NUMBNESS ||
        			this == Pain.Symptoms.WEAK_UNCOORDINATED_HANDS
        		) from $symptoms, 
        	count($t)
        )
    then
        modify($p) { 
        	setPainLocalization(Pain.PainLocalization.CERVICAL), 
        	setPainType(Pain.PainType.NEUROLOGICAL); 
        }
        
end



rule "Classify pain - Thoracal Mechanical"

    when
    	$d : Diagnosis(illness == null)
        $p : Pain(
        	painType == null, painLocalization == null,
        	$symptoms: symptoms
        )
        Number($value: intValue > 1) from accumulate(
        	Pain.Symptoms(
        			$t: this, 
        			this == Pain.Symptoms.NECK_TO_BACK_PAIN ||
        			this == Pain.Symptoms.SCAPULA_PAIN ||
        			this == Pain.Symptoms.MUSCLE_SPASM
        		) from $symptoms, 
        	count($t)
        )
    then
        modify($p) { 
        	setPainLocalization(Pain.PainLocalization.THORACAL), 
        	setPainType(Pain.PainType.MECHANICAL); 
        }
        
end



rule "Classify pain - Thoracal Neurological"

    when
    	$d : Diagnosis(illness == null)
        $p : Pain(
        	painType == null, painLocalization == null,
        	$symptoms: symptoms
        )
        Number($value: intValue > 2) from accumulate(
        	Pain.Symptoms(
        			$t: this, 
        			this == Pain.Symptoms.SHARP_THORACAL_PAIN ||
        			this == Pain.Symptoms.THORACAL_NUMBNESS ||
        			this == Pain.Symptoms.LEG_PAIN_AND_SPASM ||
        			this == Pain.Symptoms.MOVEMENT_PAIN
        		) from $symptoms, 
        	count($t)
        )
    then
        modify($p) { 
        	setPainLocalization(Pain.PainLocalization.THORACAL), 
        	setPainType(Pain.PainType.NEUROLOGICAL); 
        }
        
end



rule "Classify pain - Lumbal Mechanical"

    when
    	$d : Diagnosis(illness == null)
        $p : Pain(
        	painType == null, painLocalization == null,
        	$symptoms: symptoms
        )
        
        Pain.Symptoms(this == Pain.Symptoms.LOIN_PAIN) from $symptoms
        Pain.Symptoms(this == Pain.Symptoms.EXTERTION_PAIN) from $symptoms
        Pain.Symptoms(this == Pain.Symptoms.MOVEMENT_PAIN) from $symptoms
    then
        modify($p) { 
        	setPainLocalization(Pain.PainLocalization.LUMBAL), 
        	setPainType(Pain.PainType.MECHANICAL); 
        }
        
end



rule "Classify pain - Lumbal Neurological"

    when
    	$d : Diagnosis(illness == null)
        $p : Pain(
        	painType == null, painLocalization == null,
        	$symptoms: symptoms
        )
        Number($value: intValue > 3) from accumulate(
        	Pain.Symptoms(
        			$t: this, 
        			this == Pain.Symptoms.MOVEMENT_PAIN ||
        			this == Pain.Symptoms.REST_PAIN ||
        			this == Pain.Symptoms.LUMBAL_SPINE_DEGENERATION ||
        			this == Pain.Symptoms.SHARP_LUMBAL_SACRAL_PAIN ||
        			this == Pain.Symptoms.LEG_SPREADING_SYMPTOMS ||
        			this == Pain.Symptoms.LUMBAL_SACRAL_IMMOBILITY ||
        			this == Pain.Symptoms.LEG_IMMOBILITY
        		) from $symptoms, 
        	count($t)
        )
    then
        modify($p) { 
        	setPainLocalization(Pain.PainLocalization.LUMBAL), 
        	setPainType(Pain.PainType.NEUROLOGICAL); 
        }
        
end



rule "Set diagnosis - Acute cervical syndrome"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.MECHANICAL, painLocalization == Pain.PainLocalization.CERVICAL,
			$symptoms: symptoms, $precursors: precursors
		)
		Pain.Precursors(
			this == Pain.Precursors.INTENSE_SUDDEN_MOVEMENT ||
			this == Pain.Precursors.HOT_COLD_TEMPERATURE_CHANGE ||
			this == Pain.Precursors.COLD_TEMPERATURES
		) from $precursors
		List(size < 2) from collect(
			Diagnosis(
				illness == Diagnosis.Illness.ACUTE_CERVICAL_SYNDROME, 
				$date: diagnosisDate,
				$date.isAfter(LocalDate.now().minusMonths(5))
			) from $diagnoses
		)
	then
		System.out.println("Dijagnostifikovano: ACUTE CERVICAL SYNDROME");
		modify ($d) { 
			setIllness(Diagnosis.Illness.ACUTE_CERVICAL_SYNDROME),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end


rule "Set diagnosis - Primary cervical syndrome A"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.MECHANICAL, painLocalization == Pain.PainLocalization.CERVICAL,
			$symptoms: symptoms, $precursors: precursors
		)
		Pain.Precursors(
			this == Pain.Precursors.PROLONGED_UNCONFORTABLE_POSITION ||
			this == Pain.Precursors.BAD_POSTURE ||
			this == Pain.Precursors.LACK_PHYSICAL_ACTIVITY
		) from $precursors
		List(size < 2) from collect(
			Diagnosis(
				illness == Diagnosis.Illness.PRIMARY_CERVICAL_SYNDROME, 
				$date: diagnosisDate,
				$date.isAfter(LocalDate.now().minusMonths(5))
			) from $diagnoses
		)
	then
		System.out.println("Dijagnostifikovano: PRIMARY CERVICAL SYNDROME A");
		modify ($d) { 
			setIllness(Diagnosis.Illness.PRIMARY_CERVICAL_SYNDROME),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Primary cervical syndrome B"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.MECHANICAL, painLocalization == Pain.PainLocalization.CERVICAL,
			$symptoms: symptoms, $precursors: precursors
		)
		not Pain.Precursors(
			this == Pain.Precursors.MYOGELOSIS
		) from $precursors
		List(size >= 2) from collect(
			Diagnosis(
				illness == Diagnosis.Illness.ACUTE_CERVICAL_SYNDROME, 
				$date: diagnosisDate,
				$date.isAfter(LocalDate.now().minusMonths(5))
			) from $diagnoses
		)
	then
		System.out.println("Dijagnostifikovano: PRIMARY CERVICAL SYNDROME B");
		modify ($d) { 
			setIllness(Diagnosis.Illness.PRIMARY_CERVICAL_SYNDROME),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Cervical spondylosis A"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.MECHANICAL, painLocalization == Pain.PainLocalization.CERVICAL,
			$symptoms: symptoms, $precursors: precursors
		)
		not Pain.Precursors(
			this == Pain.Precursors.COLD_TEMPERATURES ||
			this == Pain.Precursors.HOT_COLD_TEMPERATURE_CHANGE ||
			this == Pain.Precursors.INTENSE_SUDDEN_MOVEMENT
		) from $precursors
		List(size >= 2) from collect(
			Diagnosis(
				illness == Diagnosis.Illness.PRIMARY_CERVICAL_SYNDROME, 
				$date: diagnosisDate,
				$date.isAfter(LocalDate.now().minusMonths(5))
			) from $diagnoses
		)
	then
		System.out.println("Dijagnostifikovano: CERVICAL SPONDYLOSIS A");
		modify ($d) { 
			setIllness(Diagnosis.Illness.CERVICAL_SPONDYLOSIS),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Cervical spondylosis B"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.MECHANICAL, painLocalization == Pain.PainLocalization.CERVICAL,
			$symptoms: symptoms, $precursors: precursors
		)
		Pain.Precursors(
			this == Pain.Precursors.MYOGELOSIS
		) from $precursors
	then
		System.out.println("Dijagnostifikovano: CERVICAL SPONDYLOSIS B");
		modify ($d) { 
			setIllness(Diagnosis.Illness.CERVICAL_SPONDYLOSIS),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Cervical discus hernia A"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.NEUROLOGICAL, painLocalization == Pain.PainLocalization.CERVICAL,
			$symptoms: symptoms, $precursors: precursors
		)
		Pain.Precursors(
			this == Pain.Precursors.INTENSE_SUDDEN_MOVEMENT ||
			this == Pain.Precursors.NECK_EXTERTION
		) from $precursors
	then
		System.out.println("Dijagnostifikovano: CERVICAL DISCUS HERNIA A");
		modify ($d) { 
			setIllness(Diagnosis.Illness.CERVICAL_DISCUS_HERNIA),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Cervical discus hernia B"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.NEUROLOGICAL, painLocalization == Pain.PainLocalization.CERVICAL,
			$symptoms: symptoms, $precursors: precursors
		)
		List(size > 3) from collect(
			Diagnosis(
				illness == Diagnosis.Illness.ACUTE_CERVICAL_SYNDROME || 
				illness == Diagnosis.Illness.PRIMARY_CERVICAL_SYNDROME ||
				illness == Diagnosis.Illness.CERVICAL_SPONDYLOSIS ||
				illness == Diagnosis.Illness.CERVICAL_DISCUS_HERNIA, 
				$date: diagnosisDate,
				$date.isAfter(LocalDate.now().minusMonths(12))
			) from $diagnoses
		)
	then
		System.out.println("Dijagnostifikovano: CERVICAL DISCUS HERNIA B");
		modify ($d) { 
			setIllness(Diagnosis.Illness.CERVICAL_DISCUS_HERNIA),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Thoracic syndrom A"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.MECHANICAL, painLocalization == Pain.PainLocalization.THORACAL,
			$symptoms: symptoms, $precursors: precursors
		)
		not Pain.Precursors(this == Pain.Precursors.MYOGELOSIS) from $precursors
		Pain.Precursors(
			this == Pain.Precursors.BAD_POSTURE ||
			this == Pain.Precursors.UNDEVELOPED_THORACAL_MUSCULATURE ||
			this == Pain.Precursors.KYPHO_SCOLIOSIS
		) from $precursors
	then
		System.out.println("Dijagnostifikovano: THORACIC SYNDROME A");
		modify ($d) { 
			setIllness(Diagnosis.Illness.THORACIC_SYNDROME),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Thoracic syndrom B"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.MECHANICAL, painLocalization == Pain.PainLocalization.THORACAL,
			$symptoms: symptoms, $precursors: precursors
		)
		not Pain.Precursors(
			this == Pain.Precursors.MYOGELOSIS
		) from $precursors
		List(size > 0) from collect(
			Diagnosis(
				illness == Diagnosis.Illness.ACUTE_CERVICAL_SYNDROME || 
				illness == Diagnosis.Illness.PRIMARY_CERVICAL_SYNDROME,
				$date: diagnosisDate,
				$date.isAfter(LocalDate.now().minusMonths(1))
			) from $diagnoses
		)
	then
		System.out.println("Dijagnostifikovano: THORACIC SYNDROME B");
		modify ($d) { 
			setIllness(Diagnosis.Illness.THORACIC_SYNDROME),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Thoracic spondylosis A"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.MECHANICAL, painLocalization == Pain.PainLocalization.THORACAL,
			$symptoms: symptoms, $precursors: precursors
		)
		Pain.Precursors(
			this == Pain.Precursors.MYOGELOSIS
		) from $precursors
	then
		System.out.println("Dijagnostifikovano: THORACIC_SPONDYLOSIS A");
		modify ($d) { 
			setIllness(Diagnosis.Illness.THORACIC_SPONDYLOSIS),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Thoracic spondylosis B"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.MECHANICAL, painLocalization == Pain.PainLocalization.THORACAL,
			$symptoms: symptoms, $precursors: precursors
		)
		Pain.Symptoms(
			this == Pain.Symptoms.RIB_TO_SPINE_JOINT_PAIN ||
			this == Pain.Symptoms.BREATHING_PAIN
			
		) from $symptoms
	then
		System.out.println("Dijagnostifikovano: THORACIC_SPONDYLOSIS B");
		modify ($d) { 
			setIllness(Diagnosis.Illness.THORACIC_SPONDYLOSIS),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Thoracic discus hernia B"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.NEUROLOGICAL, painLocalization == Pain.PainLocalization.THORACAL,
			$symptoms: symptoms, $precursors: precursors
		)
		List(size > 3) from collect(
			Diagnosis(
				illness == Diagnosis.Illness.THORACIC_SYNDROME || 
				illness == Diagnosis.Illness.THORACIC_SPONDYLOSIS ||
				illness == Diagnosis.Illness.THORACIC_DISCUS_HERNIA,
				$date: diagnosisDate,
				$date.isAfter(LocalDate.now().minusMonths(12))
			) from $diagnoses
		)
	then
		System.out.println("Dijagnostifikovano: THORACIC_DISCUS_HERNIA B");
		modify ($d) { 
			setIllness(Diagnosis.Illness.THORACIC_DISCUS_HERNIA),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Thoracic discus hernia A"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.NEUROLOGICAL, painLocalization == Pain.PainLocalization.THORACAL,
			$symptoms: symptoms, $precursors: precursors
		)
		Pain.Symptoms(
			this == Pain.Symptoms.THORACAL_NUMBNESS ||
			this == Pain.Symptoms.MOVEMENT_PAIN
			
		) from $symptoms
	then
		System.out.println("Dijagnostifikovano: THORACIC_DISCUS_HERNIA A");
		modify ($d) { 
			setIllness(Diagnosis.Illness.THORACIC_DISCUS_HERNIA),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end



rule "Set diagnosis - Lumbal syndrome"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.MECHANICAL, painLocalization == Pain.PainLocalization.LUMBAL,
			$symptoms: symptoms, $precursors: precursors
		)
		Pain.Precursors(
			this == Pain.Precursors.OBESITY ||	
			this == Pain.Precursors.INTENSE_SUDDEN_MOVEMENT ||
			this == Pain.Precursors.BACK_EXTERTION	
		) from $precursors
		List(size < 2) from collect(
			Diagnosis(
				illness == Diagnosis.Illness.LUMBAL_SYNDROME,
				$date: diagnosisDate,
				$date.isAfter(LocalDate.now().minusMonths(5))
			) from $diagnoses
		)
	then
		System.out.println("Dijagnostifikovano: LUMBAL_SYNDROME");
		modify ($d) { 
			setIllness(Diagnosis.Illness.LUMBAL_SYNDROME),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Lumbago A"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.MECHANICAL, painLocalization == Pain.PainLocalization.LUMBAL,
			$symptoms: symptoms, $precursors: precursors
		)
		Pain.Precursors(
			this == Pain.Precursors.LACK_PHYSICAL_ACTIVITY ||
			this == Pain.Precursors.BACK_STRAINING_PROFESSION
			
		) from $precursors
	then
		System.out.println("Dijagnostifikovano: LUMBAGO A");
		modify ($d) { 
			setIllness(Diagnosis.Illness.LUMBAGO),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Lumbago B"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.MECHANICAL, painLocalization == Pain.PainLocalization.LUMBAL,
			$symptoms: symptoms, $precursors: precursors
		)
		List(size >= 2) from collect(
			Diagnosis(
				illness == Diagnosis.Illness.LUMBAL_SYNDROME, 
				$date: diagnosisDate,
				$date.isAfter(LocalDate.now().minusMonths(5))
			) from $diagnoses
		)
	then
		System.out.println("Dijagnostifikovano: LUMBAGO B");
		modify ($d) { 
			setIllness(Diagnosis.Illness.LUMBAGO),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Lumbal discus hernia B"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.NEUROLOGICAL, painLocalization == Pain.PainLocalization.LUMBAL,
			$symptoms: symptoms, $precursors: precursors
		)
		List(size > 3) from collect(
			Diagnosis(
				illness == Diagnosis.Illness.LUMBAGO ||
				illness == Diagnosis.Illness.LUMBAL_SYNDROME, 
				$date: diagnosisDate,
				$date.isAfter(LocalDate.now().minusMonths(12))
			) from $diagnoses
		)
	then
		System.out.println("Dijagnostifikovano: LUMBAL DISCUS HERNIA B");
		modify ($d) { 
			setIllness(Diagnosis.Illness.LUMBAL_DISCUS_HERNIA),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Lumbal discus hernia A"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.NEUROLOGICAL, painLocalization == Pain.PainLocalization.LUMBAL,
			$symptoms: symptoms, $precursors: precursors
		)
		Pain.Symptoms(this == Pain.Symptoms.LEG_TINGLING_BURNING) from $symptoms
	then
		System.out.println("Dijagnostifikovano: LUMBAL_DISCUS_HERNIA A");
		modify ($d) { 
			setIllness(Diagnosis.Illness.LUMBAL_DISCUS_HERNIA),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end

rule "Set diagnosis - Sciatica"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(illness == null)
		$p : Pain(
			painType == Pain.PainType.NEUROLOGICAL, painLocalization == Pain.PainLocalization.LUMBAL,
			$symptoms: symptoms, $precursors: precursors
		)
		Pain.Symptoms(this == Pain.Symptoms.LEG_ELECTRIC_PAIN) from $symptoms
	then
		System.out.println("Dijagnostifikovano: SCIATICA");
		modify ($d) { 
			setIllness(Diagnosis.Illness.SCIATICA),
			setPain($p),
			setDiagnosisDate(LocalDate.now());
		}
end



rule "Set pain intensity - No previous conditions"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(painIntensity == null, $currentIllness: illness)
		$p : Pain(
			$simplePainIntensity: simplePainIntensity
		)
		not Diagnosis(
				$painIntensity: painIntensity,
				$painIntensity.ordinal() <= $simplePainIntensity.ordinal(),
				$diagnosisIllness: illness,
				$diagnosisIllness == $currentIllness,
				$date: diagnosisDate,
				$date.isAfter(LocalDate.now().minusMonths(3))
			) from $diagnoses
	then
		System.out.println("Klinicka slika: Dijagnostifikovana");
		modify ($d) { 
			setPainIntensity(Diagnosis.PainIntensity.values()[$simplePainIntensity.ordinal()]);
		}
		modify($pt) { addDiagnosis($d); }
end



rule "Set pain intensity - Previous conditions"

	when
		$pt: Patient($diagnoses: diagnoses)
		$d : Diagnosis(painIntensity == null, $currentIllness: illness)
		$p : Pain(
			$simplePainIntensity: simplePainIntensity
		)
		Diagnosis(
				$painIntensity: painIntensity,
				$painIntensity.ordinal() <= $simplePainIntensity.ordinal(),
				$diagnosisIllness: illness,
				$diagnosisIllness == $currentIllness,
				$date: diagnosisDate,
				$date.isAfter(LocalDate.now().minusMonths(3))
			) from $diagnoses
	then
		System.out.println("Klinicka slika: Dijagnostifikovana");
		modify ($d) { 
			setPainIntensity(Diagnosis.PainIntensity.WORSENING);
		}
		modify($pt) { addDiagnosis($d); }
end

		
rule "Set therapy - Acute Cervical Syndrome - Medium to Mild"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.MILD || painIntensity == Diagnosis.PainIntensity.MEDIUM, 
			illness == Diagnosis.Illness.ACUTE_CERVICAL_SYNDROME, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.DIODYNAMIC_ELLECTROCURRENTS,
			10, "Vratni deo"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.MASSAGE,
			10, "Vratni i rameni pojas"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.CHIROPRACTIC_ADJUSTMENT,
			10, "Vratni i rameni pojas"
		);
		Excercise statickaFleksija = new Excercise(
			1L, Excercise.Type.STATIC,
			10, "Staticka fleksija glave"
		);
		Excercise statickaRotacija = new Excercise(
			2L, Excercise.Type.STATIC,
			10, "Staticka rotacija glave"
		);
		Excercise statickaEkstenzija = new Excercise(
			3L, Excercise.Type.STATIC,
			10, "Staticka ekstenzija glave"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addExcercise(statickaFleksija),
			addExcercise(statickaRotacija),
			addExcercise(statickaEkstenzija);
		}
end
		
			
			
rule "Set therapy - Acute Cervical Syndrome - Strong"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.STRONG, 
			illness == Diagnosis.Illness.ACUTE_CERVICAL_SYNDROME, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.ULTRASOUD,
			10, "Vratni i rameni deo"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.LASER,
			10, "Vratni deo"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.BIOPTRON_LAMP,
			10, "Vratni deo"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3);
		}
end		



rule "Set therapy - Acute Cervical Syndrome - Worsening"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.WORSENING, 
			illness == Diagnosis.Illness.ACUTE_CERVICAL_SYNDROME, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Excercise statickaFleksija = new Excercise(
			1L, Excercise.Type.STATIC,
			10, "Staticka fleksija glave"
		);
		Excercise statickaRotacija = new Excercise(
			2L, Excercise.Type.STATIC,
			10, "Staticka rotacija glave"
		);
		Excercise statickaEkstenzija = new Excercise(
			3L, Excercise.Type.STATIC,
			10, "Staticka ekstenzija glave"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addExcercise(statickaFleksija),
			addExcercise(statickaRotacija),
			addExcercise(statickaEkstenzija);
		}
end	



rule "Set therapy - Primary Cervical Syndrome - Mild"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.MILD, 
			illness == Diagnosis.Illness.PRIMARY_CERVICAL_SYNDROME, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.DIODYNAMIC_ELLECTROCURRENTS,
			10, "Vratni deo"
		);
		Excercise fleksija = new Excercise(
			1L, Excercise.Type.DYNAMIC,
			15, "Fleksija glave"
		);
		Excercise rotacija = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			15, "Rotacija glave"
		);
		Excercise ekstenzija = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			15, "Ekstenzija glave"
		);
		Excercise bocnaFleksija = new Excercise(
			4L, Excercise.Type.DYNAMIC,
			15, "Bocna fleksija glave"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addExcercise(fleksija),
			addExcercise(rotacija),
			addExcercise(ekstenzija),
			addExcercise(bocnaFleksija);
		}
end



rule "Set therapy - Primary Cervical Syndrome - Medium"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.MEDIUM, 
			illness == Diagnosis.Illness.PRIMARY_CERVICAL_SYNDROME, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.MASSAGE,
			10, "Vratni i rameni pojas"
		);
		Excercise fleksija = new Excercise(
			1L, Excercise.Type.DYNAMIC,
			15, "Fleksija glave"
		);
		Excercise rotacija = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			15, "Rotacija glave"
		);
		Excercise ekstenzija = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			15, "Ekstenzija glave"
		);
		Excercise bocnaFleksija = new Excercise(
			4L, Excercise.Type.DYNAMIC,
			15, "Bocna fleksija glave"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addExcercise(fleksija),
			addExcercise(rotacija),
			addExcercise(ekstenzija),
			addExcercise(bocnaFleksija);
		}
end



rule "Set therapy - Primary Cervical Syndrome - Strong"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.STRONG, 
			illness == Diagnosis.Illness.PRIMARY_CERVICAL_SYNDROME, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.INTERFERENCE_CURRENTS,
			10, "Vratni deo"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.CHIROPRACTIC_ADJUSTMENT,
			10, "Vratni i rameni deo"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.MASSAGE,
			10, "Vratni i rameni pojas"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3);
		}
end	


	
rule "Set therapy - Primary Cervical Syndrome - Worsening"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.WORSENING, 
			illness == Diagnosis.Illness.PRIMARY_CERVICAL_SYNDROME, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Excercise fleksija = new Excercise(
			1L, Excercise.Type.DYNAMIC,
			15, "Fleksija glave"
		);
		Excercise rotacija = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			15, "Rotacija glave"
		);
		Excercise ekstenzija = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			15, "Ekstenzija glave"
		);
		Excercise bocnaFleksija = new Excercise(
			4L, Excercise.Type.DYNAMIC,
			15, "Bocna fleksija glave"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addExcercise(fleksija),
			addExcercise(rotacija),
			addExcercise(ekstenzija),
			addExcercise(bocnaFleksija);
		}
end

rule "Set therapy - Cervical Spondylosis - Mild Medium Strong "
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.MILD || painIntensity == Diagnosis.PainIntensity.MEDIUM
			|| painIntensity == Diagnosis.PainIntensity.STRONG, 
			illness == Diagnosis.Illness.CERVICAL_SPONDYLOSIS, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.DIODYNAMIC_ELLECTROCURRENTS,
			10, "Vratni i rameni deo"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.ULTRASOUD,
			10, "Vratni i rameni deo"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.LASER,
			10, "Vratni deo"
		);
		Therapy t4 = new Therapy(
			Therapy.TherapyType.MASSAGE,
			10, "Vratni i rameni pojas"
		);
		Therapy t5 = new Therapy(
			Therapy.TherapyType.CHIROPRACTIC_ADJUSTMENT,
			10, "Vratni deo"
		);
		Excercise statickaFleksija = new Excercise(
			1L, Excercise.Type.STATIC,
			10, "Staticka fleksija glave"
		);
		Excercise statickaRotacija = new Excercise(
			2L, Excercise.Type.STATIC,
			10, "Staticka rotacija glave"
		);
		Excercise statickaEkstenzija = new Excercise(
			3L, Excercise.Type.STATIC,
			10, "Staticka ekstenzija glave"
		);
		Excercise fleksija = new Excercise(
			1L, Excercise.Type.DYNAMIC,
			15, "Fleksija glave"
		);
		Excercise rotacija = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			15, "Rotacija glave"
		);
		Excercise ekstenzija = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			15, "Ekstenzija glave"
		);
		Excercise bocnaFleksija = new Excercise(
			4L, Excercise.Type.DYNAMIC,
			15, "Bocna fleksija glave"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addTherapy(t4),
			addTherapy(t5),
			addExcercise(statickaFleksija),
			addExcercise(statickaRotacija),
			addExcercise(statickaEkstenzija),
			addExcercise(fleksija),
			addExcercise(rotacija),
			addExcercise(ekstenzija),
			addExcercise(bocnaFleksija);
		}
end


rule "Set therapy - Cervical Spondylosis - Worsening"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.WORSENING, 
			illness == Diagnosis.Illness.CERVICAL_SPONDYLOSIS, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.DIODYNAMIC_ELLECTROCURRENTS,
			10, "Vratni i rameni deo"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.ULTRASOUD,
			10, "Vratni i rameni deo"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.LASER,
			10, "Vratni deo"
		);
		Therapy t4 = new Therapy(
			Therapy.TherapyType.MASSAGE,
			10, "Vratni i rameni pojas"
		);
		Therapy t5 = new Therapy(
			Therapy.TherapyType.CHIROPRACTIC_ADJUSTMENT,
			10, "Vratni deo"
		);
		Therapy t6 = new Therapy(
			Therapy.TherapyType.ELECTRO_PHORESYS_NOVOCAINE,
			10, "Vratni deo"
		);
		Excercise statickaFleksija = new Excercise(
			1L, Excercise.Type.STATIC,
			10, "Staticka fleksija glave"
		);
		Excercise statickaRotacija = new Excercise(
			2L, Excercise.Type.STATIC,
			10, "Staticka rotacija glave"
		);
		Excercise statickaEkstenzija = new Excercise(
			3L, Excercise.Type.STATIC,
			10, "Staticka ekstenzija glave"
		);
		Excercise fleksija = new Excercise(
			1L, Excercise.Type.DYNAMIC,
			15, "Fleksija glave"
		);
		Excercise rotacija = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			15, "Rotacija glave"
		);
		Excercise ekstenzija = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			15, "Ekstenzija glave"
		);
		Excercise bocnaFleksija = new Excercise(
			4L, Excercise.Type.DYNAMIC,
			15, "Bocna fleksija glave"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addTherapy(t4),
			addTherapy(t5),
			addTherapy(t6),
			addExcercise(statickaFleksija),
			addExcercise(statickaRotacija),
			addExcercise(statickaEkstenzija),
			addExcercise(fleksija),
			addExcercise(rotacija),
			addExcercise(ekstenzija),
			addExcercise(bocnaFleksija);
		}
end

rule "Set therapy - Cervical Discus Hernia - Mild Medium Strong "
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.MILD || painIntensity == Diagnosis.PainIntensity.MEDIUM
			|| painIntensity == Diagnosis.PainIntensity.STRONG, 
			illness == Diagnosis.Illness.CERVICAL_DISCUS_HERNIA, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.BIOPTRON_LAMP,
			10, "Vratni deo"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.ELECTRO_PHORESYS_B_VIT,
			10, "Vratni deo i saka"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.LASER,
			10, "Vratni deo"
		);
		Therapy t4 = new Therapy(
			Therapy.TherapyType.MAGNETOTHERAPY,
			10, "Vratni deo i duz ruke"
		);
		Excercise mirovanje = new Excercise(
			1L, Excercise.Type.REST,
			10, "Sancov okovratnik i mirovanje"
		);
		
		Excercise kineziterapija = new Excercise(
			1L, Excercise.Type.STATIC,
			10, "Kineziterapija"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addTherapy(t4),
			addExcercise(mirovanje),
			addExcercise(kineziterapija);
		}
end

rule "Set therapy - Cervical Discus Hernia - Worsening"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.WORSENING, 
			illness == Diagnosis.Illness.CERVICAL_DISCUS_HERNIA, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.LASER,
			10, ""
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.ELECTRO_PHORESYS_B_VIT,
			10, "Vratni deo i saka"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.BIOPTRON_LAMP,
			10, "Vratni deo"
		);
		Therapy t4 = new Therapy(
			Therapy.TherapyType.MAGNETOTHERAPY,
			10, "Vratni deo i duz ruke"
		);
		Therapy t5 = new Therapy(
			Therapy.TherapyType.DIODYNAMIC_ELLECTROCURRENTS,
			10, "Vratni deo i saka"
		);
		
		Therapy t6 = new Therapy(
			Therapy.TherapyType.REST,
			10, "Skidanje okovratnika"
		);
		Excercise kineziterapija = new Excercise(
			1L, Excercise.Type.REST,
			10, "Kineziterapija uz skidanje okovratnika"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addTherapy(t4),
			addTherapy(t5),
			addTherapy(t6),
			addExcercise(kineziterapija);
		}
end

rule "Set therapy - Thoracic Syndrom - Mild Medium"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.MILD || painIntensity == Diagnosis.PainIntensity.MEDIUM, 
			illness == Diagnosis.Illness.THORACIC_SYNDROME, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.DIODYNAMIC_ELLECTROCURRENTS,
			1, "Izmedju lopatica i bolna mesta"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.BIOPTRON_LAMP,
			1, "Izmedju lopatica"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.CHIROPRACTIC_ADJUSTMENT,
			1, ""
		);
		
		Excercise trbusniMisici = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			12, "trbusnjaci, ukrsteni trbusnjaci, leg raise"
		);
		
		Excercise ledjniMisici = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			12, "ledjnjaci, dizanje lakih tegova lezeci sa poda, sipka iza vrata"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addExcercise(trbusniMisici),
			addExcercise(ledjniMisici);
		}
end

rule "Set therapy - Thoracic Syndrom - Strong Worsening"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.STRONG || painIntensity == Diagnosis.PainIntensity.WORSENING, 
			illness == Diagnosis.Illness.THORACIC_SYNDROME, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.BIOPTRON_LAMP,
			1, "Izmedju lopatica"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.CHIROPRACTIC_ADJUSTMENT,
			1, ""
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.ELECTRO_PHORESYS_NOVOCAINE,
			1, "Na bolna mesta"
		);
		Therapy t4 = new Therapy(
			Therapy.TherapyType.MASSAGE,
			1, "Rameni pojas izmedju lopatica"
		);
		Excercise trbusniMisici = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			12, "trbusnjaci, ukrsteni trbusnjaci, leg raise"
		);
		
		Excercise ledjniMisici = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			12, "ledjnjaci, dizanje lakih tegova lezeci sa poda, sipka iza vrata"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addTherapy(t4),
			addExcercise(trbusniMisici),
			addExcercise(ledjniMisici);
		}
end

rule "Set therapy - Thoracic Spondylosis - Mild Medium"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.MILD || painIntensity == Diagnosis.PainIntensity.MEDIUM, 
			illness == Diagnosis.Illness.THORACIC_SPONDYLOSIS, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.ELECTRO_PHORESYS_NOVOCAINE,
			1, "Predeo grudne muskulature"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.ULTRASOUD,
			1, "Predeo grudne kicme"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.BIOPTRON_LAMP,
			20, "Grudna kicma"
		);
		Therapy t4 = new Therapy(
			Therapy.TherapyType.MASSAGE,
			1, ""
		);
		Therapy t5 = new Therapy(
			Therapy.TherapyType.CHIROPRACTIC_ADJUSTMENT,
			1, ""
		);
		Excercise trbusniMisici = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			12, "trbusnjaci, ukrsteni trbusnjaci, leg raise"
		);
		
		Excercise ledjniMisici = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			12, "ledjnjaci, dizanje lakih tegova lezeci sa poda, sipka iza vrata"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addTherapy(t4),
			addTherapy(t5),
			addExcercise(trbusniMisici),
			addExcercise(ledjniMisici);
		}
end

rule "Set therapy - Thoracic Spondylosis - Strong Worsening"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.STRONG || painIntensity == Diagnosis.PainIntensity.WORSENING, 
			illness == Diagnosis.Illness.THORACIC_SPONDYLOSIS, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.ELECTRO_PHORESYS_NOVOCAINE,
			1, "Predeo grudne muskulature"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.ULTRASOUD,
			1, "Predeo grudne kicme"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.BIOPTRON_LAMP,
			20, "Grudna kicma"
		);
		Therapy t4 = new Therapy(
			Therapy.TherapyType.MASSAGE,
			20, ""
		);
		Therapy t5 = new Therapy(
			Therapy.TherapyType.CHIROPRACTIC_ADJUSTMENT,
			1, ""
		);
		Therapy t6 = new Therapy(
			Therapy.TherapyType.PARAFFIN,
			1, ""
		);
		Excercise trbusniMisici = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			12, "trbusnjaci, ukrsteni trbusnjaci, leg raise"
		);
		
		Excercise ledjniMisici = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			12, "ledjnjaci, dizanje lakih tegova lezeci sa poda, sipka iza vrata"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addTherapy(t4),
			addTherapy(t5),
			addTherapy(t6),
			addExcercise(trbusniMisici),
			addExcercise(ledjniMisici);
		}
end

rule "Set therapy - Thoracic Discus Hernia - Mild Medium"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.MILD || painIntensity == Diagnosis.PainIntensity.MEDIUM, 
			illness == Diagnosis.Illness.THORACIC_DISCUS_HERNIA, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.ELECTRO_PHORESYS_NOVOCAINE,
			1, "Predeo donjeg dela grudne kicme"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.ULTRASOUD,
			1, "Predeo donjeg dela grudne kicme"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.PARAFFIN,
			20, "Predeo donjeg dela grudne kicme"
		);
		Therapy t4 = new Therapy(
			Therapy.TherapyType.LASER,
			1, "Na bolna mesta"
		);
		Excercise trbusniMisici = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			12, "trbusnjaci, ukrsteni trbusnjaci, leg raise"
		);
		
		Excercise ledjniMisici = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			12, "ledjnjaci, dizanje lakih tegova lezeci sa poda, sipka iza vrata"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addExcercise(trbusniMisici),
			addExcercise(ledjniMisici);
		}
end

rule "Set therapy - Thoracic Discus Hernia - Strong Worsening"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.STRONG || painIntensity == Diagnosis.PainIntensity.WORSENING, 
			illness == Diagnosis.Illness.THORACIC_DISCUS_HERNIA, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.ELECTRO_PHORESYS_NOVOCAINE,
			1, "Predeo donjeg dela grudne kicme"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.ULTRASOUD,
			1, "Predeo donjeg dela grudne kicme"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.PARAFFIN,
			20, "Predeo donjeg dela grudne kicme"
		);
		Therapy t4 = new Therapy(
			Therapy.TherapyType.MAGNETOTHERAPY,
			1, ""
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3);
		}
end

rule "Set therapy - Lumbal Syndrom - Mild Medium"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.MILD || painIntensity == Diagnosis.PainIntensity.MEDIUM, 
			illness == Diagnosis.Illness.LUMBAL_SYNDROME, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.DIODYNAMIC_ELLECTROCURRENTS,
			1, "Lumbalni deo"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.ULTRASOUD,
			1, "Lumbalni deo"
		);
		Excercise trbusniMisici = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			10, "trbusnjaci, ukrsteni trbusnjaci, leg raise, lezece ravnanje kicme, lezece ravnaje kicme+dizanje glave"
		);
		
		Excercise ledjniMisici = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			12, "ledjnjaci, dizanje lakih tegova lezeci sa poda, sipka iza vrata, most savijenih i ispruzenih ruku"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addExcercise(trbusniMisici),
			addExcercise(ledjniMisici);
		}
end

rule "Set therapy - Lumbal Syndrom - Strong"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.STRONG || painIntensity == Diagnosis.PainIntensity.WORSENING,
			illness == Diagnosis.Illness.LUMBAL_SYNDROME, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.DIODYNAMIC_ELLECTROCURRENTS,
			1, "Lumbalni deo"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.ULTRASOUD,
			1, "Lumbalni deo"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.MASSAGE,
			1, ""
		);
		Excercise trbusniMisici = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			10, "trbusnjaci, ukrsteni trbusnjaci, leg raise, lezece ravnanje kicme, lezece ravnaje kicme+dizanje glave"
		);
		
		Excercise ledjniMisici = new Excercise(
			3L, Excercise.Type.DYNAMIC,
			12, "ledjnjaci, dizanje lakih tegova lezeci sa poda, sipka iza vrata, most savijenih i ispruzenih ruku"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addExcercise(trbusniMisici),
			addExcercise(ledjniMisici);
		}
end

rule "Set therapy - Lumbago - Mild Medium"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.MILD || painIntensity == Diagnosis.PainIntensity.MEDIUM, 
			illness == Diagnosis.Illness.LUMBAGO, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.DIODYNAMIC_ELLECTROCURRENTS,
			1, "Lumbalni deo"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.ULTRASOUD,
			1, "Lumbalni deo"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.ELECTRO_PHORESYS_NOVOCAINE,
			1, "Lumbalni deo"
		);
		Excercise trbusniMisici = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			12, "trbusnjaci, ukrsteni trbusnjaci, leg raise"
		);
		
		Excercise ledjniMisici = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			12, "ledjnjaci, dizanje lakih tegova lezeci sa poda, sipka iza vrata"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addExcercise(trbusniMisici),
			addExcercise(ledjniMisici);
		}
end

rule "Set therapy - Lumbago - Strong Worsening"
	when 
		$t : Treatment(patient == null, diagnosis == null)
		$pt: Patient()
		$d : Diagnosis(
			painIntensity == Diagnosis.PainIntensity.STRONG || painIntensity == Diagnosis.PainIntensity.WORSENING, 
			illness == Diagnosis.Illness.LUMBAGO, 
			$painIntensity: painIntensity, $illnes: illness
		)
	then 
		Therapy t1 = new Therapy(
			Therapy.TherapyType.DIODYNAMIC_ELLECTROCURRENTS,
			1, "Lumbalni deo"
		);
		Therapy t2 = new Therapy(
			Therapy.TherapyType.ULTRASOUD,
			1, "Lumbalni deo"
		);
		Therapy t3 = new Therapy(
			Therapy.TherapyType.ELECTRO_PHORESYS_NOVOCAINE,
			1, "Lumbalni deo"
		);
		Therapy t4 = new Therapy(
			Therapy.TherapyType.MAGNETOTHERAPY,
			1, "Lumbalni deo"
		);
		Therapy t5 = new Therapy(
			Therapy.TherapyType.PARAFFIN,
			1, "Krstacni deo"
		);
		Therapy t6 = new Therapy(
			Therapy.TherapyType.LASER,
			1, "Bolna mesta"
		);
		Excercise trbusniMisici = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			12, "trbusnjaci, ukrsteni trbusnjaci, leg raise"
		);
		
		Excercise ledjniMisici = new Excercise(
			2L, Excercise.Type.DYNAMIC,
			12, "ledjnjaci, dizanje lakih tegova lezeci sa poda, sipka iza vrata"
		);
		modify ($t) {
			setPatient($pt),
			setDiagnosis($d),
			addTherapy(t1),
			addTherapy(t2),
			addTherapy(t3),
			addTherapy(t4),
			addTherapy(t5),
			addTherapy(t6),
			addExcercise(trbusniMisici),
			addExcercise(ledjniMisici);
		}
end