package com.sbnz;
import com.sbnz.physio.facts.Pain.PainType;
import com.sbnz.physio.facts.Pain.PainLocalization;
import com.sbnz.physio.facts.Pain.Symptoms;
import com.sbnz.physio.facts.Pain.Precursors;
import com.sbnz.physio.facts.Diagnosis.Illness;
import com.sbnz.physio.facts.Diagnosis.PainIntensity;
import com.sbnz.physio.facts.Therapy.TherapyType;
import com.sbnz.physio.facts.*;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.HashSet;

rule "Set Therapy_0"
when
	$t : Treatment(patient == null, diagnosis == null)
	$pt: Patient()
	$d : Diagnosis(
		painIntensity memberOf [PainIntensity.MILD, PainIntensity.MEDIUM], 
		illness == Illness.PRIMARY_CERVICAL_SYNDROME, 
		$painIntensity: painIntensity, $illnes: illness
	)
then
	System.out.println("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA NMG");
	modify($t) { 
		setTherapies(new HashSet<Therapy>(Arrays.asList(
			new Therapy(TherapyType.ELECTRO_PHORESYS_NOVOCAINE, 1, "predio ledja"), 
			new Therapy(TherapyType.ULTRASOUD, 1, "predio ledja"))));
	}
end