package com.cep;

//list any import classes here.

import com.sbnz.physio.facts.*;
import com.sbnz.physio.events.*;
import java.util.List;

declare WorkoutDifficultyEvent
	@role(event)
end


rule "Dynamic to static"
    when
        $t1: ExcerciseEvent(painType == ExcerciseEvent.PainType.STIFFNESS, type == Excercise.Type.DYNAMIC, $name: name)
    then
        System.out.println("Dynamic to static".toUpperCase());
        insert(new ExerciseReplacement(Excercise.Type.STATIC, $name, false));
        insert(new WorkoutDifficultyEvent());
end

rule "Static to rest"
    when
        $t1: ExcerciseEvent(type == Excercise.Type.STATIC, $name: name)
    then
    	System.out.println("Static to rest".toUpperCase());
       	insert(new ExerciseReplacement(Excercise.Type.REST, "Pacijent neka odmori malo", false));
      	insert(new WorkoutDifficultyEvent());
end


rule "Dynamic to rest"
	when 
		$t1: ExcerciseEvent(painType == ExcerciseEvent.PainType.PAIN, type == Excercise.Type.DYNAMIC)
		List (size > 0) from collect ( ExcerciseEvent(this before $t1) over window:time(10m))
		not WorkoutDifficultyEvent()
	then
		System.out.println("Dynamic to rest".toUpperCase());
		insert(new ExerciseReplacement(Excercise.Type.REST, "Pacijent neka prekine vezbe", true));
end


rule "Many mild events"
	when 
		List($brPovreda: size) from collect( 
			InjuryEvent($injury: this, severity == InjuryEvent.InjurySeverity.MILD) over window:time(20m)
		)
		List($brPremora: size) from collect(
			ExhaustionEvent($exhaustion: this) over window:time(20m)
		)
		eval($brPovreda + $brPremora > 2)
	then
		System.out.println("Many mild events".toUpperCase());
		System.out.println("Br. povreda: " + $brPovreda);
		System.out.println("Br. premora: " + $brPremora);
		insert(new WorkoutDifficultyEvent());
end		


rule "Dynamic difficulties"
	when 
		$e1: ExcerciseEvent(painType == ExcerciseEvent.PainType.PAIN, type == Excercise.Type.DYNAMIC, $name: name)
		$e2: WorkoutDifficultyEvent()
	then
		System.out.println("Dynamic difficulties".toUpperCase());
		insert(new ExerciseReplacement(Excercise.Type.STATIC, $name, false));
end

rule "Dynamic injury - no other difficulties"
	when 
		$e1: InjuryEvent(severity == InjuryEvent.Severity.SEVERE, type == Excercise.Type.DYNAMIC, $name: name)
		List (size <= 1) from collect (InjuryEvent())
		List (size == 0) from collect (ExcerciseEvent())
	then
		System.out.println("Dynamic injury - no other difficulties".toUpperCase());
		insert(new ExerciseReplacement(Excercise.Type.STATIC, $name, false));
end

rule "Dynamic injury - other difficulties"
	when 
		$e1: InjuryEvent(severity == InjuryEvent.Severity.SEVERE, type == Excercise.Type.DYNAMIC)
		List (size > 1) from collect (InjuryEvent())
		List (size > 0) from collect (ExcerciseEvent())
	then
		System.out.println("Dynamic injury - other difficulties".toUpperCase());
		insert(new ExerciseReplacement(Excercise.Type.REST, "Pacijent neka hitno prekine sa vezbanjem", true));
end
		
		

/*
rule "Many mild injuries"
	when 
		List (size > 1) from collect ( InjuryEvent(severity == InjuryEvent.InjurySeverity.MILD) over window:time(20m) )
	then
		insert(new WorkoutDifficultyEvent());
end

rule "Exhausts a lot"
	when 
		List (size > 2) from collect ( ExhaustionEvent() over window:time(20m))
	then
		insert(new WorkoutDifficultyEvent());
end

*/